# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fail_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
