# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20171214_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='paid', max_length=10),
        ),
    ]
