# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171207_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
