# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 07:27
from __future__ import unicode_literals

from django.db import migrations
import utils.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171215_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=utils.custom_imagefield.ProfileImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
