# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 09:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[(datetime.time(9, 0), '9시'), (datetime.time(10, 0), '10시'), (datetime.time(11, 0), '11시'), (datetime.time(12, 0), '12시'), (datetime.time(13, 0), '13시'), (datetime.time(14, 0), '14시'), (datetime.time(15, 0), '15시'), (datetime.time(16, 0), '16시'), (datetime.time(17, 0), '17시'), (datetime.time(18, 0), '18시'), (datetime.time(19, 0), '19시'), (datetime.time(20, 0), '20시'), (datetime.time(20, 0), '21시')], max_length=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_size', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=5)),
                ('district', models.CharField(max_length=5)),
                ('detail_address', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=11)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('restaurant_type', models.CharField(choices=[('kor', 'Korean'), ('chn', 'Chinese'), ('jpn', 'Japanese'), ('mex', 'Mexican'), ('amc', 'American'), ('tha', 'Thai'), ('med', 'Mediterranean'), ('ita', 'Italian'), ('vtn', 'Vietnamese'), ('spn', 'Spanish'), ('ind', 'Indian'), ('etc', 'Etc')], max_length=3)),
                ('average_price', models.CharField(choices=[('c', 'Cheap'), ('n', 'Normal'), ('e', 'Expensive'), ('v', 'Very Expensive')], max_length=1)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservationtable',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.ReservationTable'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='imageforrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
