# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='reservationtable',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='table',
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='acceptable_size_of_party',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_info', to='restaurants.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='maximum_party',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageforrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.Restaurant'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='ReservationTable',
        ),
    ]
