# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='strip_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
