# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20171219_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.custom_imagefield.CustomImageField(blank=True, upload_to='menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='restaurants.Restaurant')),
            ],
        ),
    ]
