# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 05:02
from __future__ import unicode_literals

from django.db import migrations
import utils.custom_imagefiled


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_strip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageforrestaurant',
            name='image',
            field=utils.custom_imagefiled.CustomImageField(blank=True, upload_to='restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=utils.custom_imagefiled.CustomImageField(blank=True, upload_to='menu'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='thumbnail',
            field=utils.custom_imagefiled.CustomImageField(blank=True, upload_to='thumbnail'),
        ),
    ]
