# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20171130_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_hours',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ImageField(default=1, upload_to='menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='star_raing',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
