# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20171204_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationinfo',
            name='open',
        ),
    ]
