# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menuimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
    ]
