# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimages',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.Restaurant'),
        ),
    ]
