# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20171229_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='thumbnail',
            new_name='main_image',
        ),
    ]
