# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20171204_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurants.Restaurant'),
        ),
    ]
