# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20171204_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star_rate',
            field=models.FloatField(choices=[(0.5, 0.5), (1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)]),
        ),
    ]
